[versions]

#Projectwide
android-minSdk = "21"
android-targetSdk = "36"
android-compileSdk = "36"

#Plugins
android-gradle-plugin = "8.13.0"
compose-plugin = "1.9.1"
kotlin = "2.2.20"
kotlinx-datetime = "0.7.1"
ktor = "3.3.0"


#A
androidx-material3-windowSizeClass-multiplatform = "0.5.0"
androidx-navigation = "2.9.1"

#B

#C

#D

#E

#F

#G

#H

#I

#J
java = "21"

#K

#L
logback = "1.5.20"

#M

#N

#O

#P

#Q

#R

#S

#T

#U

#V

#W

#X

#Y

#Z


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }



[libraries]

#AndroidX
androidx-material3-windowSizeClass-multiplatform = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "androidx-material3-windowSizeClass-multiplatform" }
androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

#KotlinX
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "ktor" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "ktor" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

#Ktor
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }

#Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

#Unit Tests
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

