[versions]

#Projectwide
android-minSdk = "21"
android-targetSdk = "35"
android-compileSdk = "35"

#Plugins
android-gradle-plugin = "8.8.0"
compose-plugin = "1.8.0-alpha01"
kotlin = "2.1.10"
ktor = "2.3.12"

#A
androidx-material3-windowSizeClass-multiplatform = "0.5.0"
androidx-navigation = "2.8.0-alpha08"

#B

#C

#D

#E

#F

#G

#H

#I

#J

#K

#L
logback = "1.5.6"

#M

#N

#O

#P

#Q

#R

#S

#T

#U

#V

#W

#X

#Y

#Z


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }



[libraries]

#AndroidX
androidx-material3-windowSizeClass-multiplatform = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "androidx-material3-windowSizeClass-multiplatform" }
androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

#Ktor
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-tests = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor" }

#Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

#Unit Tests
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

